{"name": "Запуск #1", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TargetClosedError: Page.screenshot: Target page, context or browser has been closed", "trace": "run_number = 1, load_times = []\n\n    @pytest.mark.parametrize(\"run_number\", range(1, 51))\n    @allure.title(\"Запуск #{run_number}\")\n    @allure.description(\"Запуск теста с последовательной загрузкой страницы и вводом OTP\")\n    def test_sequential_runs(run_number, load_times):\n        with sync_playwright() as playwright:\n>           run(playwright, run_number, load_times)\n\ntest_auth_with_accounts_allure.py:79: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntest_auth_with_accounts_allure.py:62: in run\n    allure.attach(page.screenshot(), name=f\"Ошибка на запуске #{run_number}\",\nC:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:9543: in screenshot\n    self._sync(\nC:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_page.py:739: in screenshot\n    encoded_binary = await self._channel.send(\"screenshot\", params)\nC:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_connection.py:59: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x0000028905CA1B20>, cb = <function Channel.send.<locals>.<lambda> at 0x0000028906115300>, is_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TargetClosedError: Page.screenshot: Target page, context or browser has been closed\n\nC:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_connection.py:514: TargetClosedError"}, "description": "Запуск теста с последовательной загрузкой страницы и вводом OTP", "steps": [{"name": "Запуск теста 1", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TargetClosedError: Page.screenshot: Target page, context or browser has been closed\n", "trace": "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\project_kicb\\webTest\\test_auth_with_accounts_allure.py\", line 62, in run\n    allure.attach(page.screenshot(), name=f\"Ошибка на запуске #{run_number}\",\n                  ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9543, in screenshot\n    self._sync(\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 739, in screenshot\n    encoded_binary = await self._channel.send(\"screenshot\", params)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "steps": [{"name": "Запуск браузера в headless режиме, запуск #1", "status": "passed", "start": 1726737023061, "stop": 1726737023330}, {"name": "Заполнение поля логина", "status": "passed", "start": 1726737032011, "stop": 1726737032042}, {"name": "Заполнение поля пароля", "status": "passed", "start": 1726737032051, "stop": 1726737036472}, {"name": "Ожидание открытия OTP ввода", "status": "passed", "start": 1726737036472, "stop": 1726737039729}, {"name": "Ожидание текста после ввода OTP", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TargetClosedError: Page.screenshot: Target page, context or browser has been closed\n", "trace": "  File \"C:\\project_kicb\\webTest\\test_auth_with_accounts_allure.py\", line 62, in run\n    allure.attach(page.screenshot(), name=f\"Ошибка на запуске #{run_number}\",\n                  ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9543, in screenshot\n    self._sync(\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 739, in screenshot\n    encoded_binary = await self._channel.send(\"screenshot\", params)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1726737039729, "stop": 1726737055499}], "attachments": [{"name": "Параметр", "source": "83d4bfef-94cd-480c-92a6-e2c7b8c58c06-attachment.attach"}, {"name": "Время начала", "source": "b042e4bd-27dd-41ea-a1f6-e7cf1dca32d8-attachment.attach"}], "parameters": [{"name": "playwright", "value": "<playwright._impl._playwright.Playwright object at 0x0000028905F78380>"}, {"name": "run_number", "value": "1"}, {"name": "load_times", "value": "[]"}], "start": 1726737023061, "stop": 1726737055500}], "parameters": [{"name": "run_number", "value": "1"}], "start": 1726737022828, "stop": 1726737055611, "uuid": "254489ee-783b-4332-8312-06c746761f3c", "historyId": "6de9a902ded0f6ff5fc7a01c175e8a57", "testCaseId": "6b78aa67c85535a7dd05d5a09b6713e2", "fullName": "test_auth_with_accounts_allure#test_sequential_runs", "labels": [{"name": "suite", "value": "test_auth_with_accounts_allure"}, {"name": "host", "value": "DESKTOP-U8CRCDT"}, {"name": "thread", "value": "15636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_auth_with_accounts_allure"}]}